# Generated by Django 3.2.5 on 2021-07-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
